<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>TestNG Report</title><style type="text/css">table {margin-bottom:10px;border-collapse:collapse;empty-cells:show}th,td {border:1px solid #009;padding:.25em .5em}th {vertical-align:bottom}td {vertical-align:top}table a {font-weight:bold}.stripe td {background-color: #E6EBF9}.num {text-align:right}.passedodd td {background-color: #3F3}.passedeven td {background-color: #0A0}.skippedodd td {background-color: #DDD}.skippedeven td {background-color: #CCC}.failedodd td,.attn {background-color: #F33}.failedeven td,.stripe .attn {background-color: #D00}.stacktrace {white-space:pre;font-family:monospace}.totop {font-size:85%;text-align:center;border-bottom:2px solid #000}</style></head><body><table><tr><th>Test</th><th># Passed</th><th># Skipped</th><th># Failed</th><th>Time (ms)</th><th>Included Groups</th><th>Excluded Groups</th></tr><tr><th colspan="7">testList</th></tr><tr><td><a href="#t0">myTest</a></td><td class="num">2</td><td class="num">0</td><td class="num attn">15</td><td class="num">143,098</td><td></td><td></td></tr></table><table><thead><tr><th>Class</th><th>Method</th><th>Start</th><th>Time (ms)</th></tr></thead><tbody><tr><th colspan="4">testList</th></tr></tbody><tbody id="t0"><tr><th colspan="4">myTest &#8212; failed</th></tr><tr class="failedeven"><td rowspan="8">com.perfectomobile.DomExe</td><td><a href="#m0">testDevices</a></td><td rowspan="8">1451401797659</td><td rowspan="8">63979</td></tr><tr class="failedeven"><td><a href="#m1">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m2">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m3">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m4">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m5">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m6">testDevices</a></td></tr><tr class="failedeven"><td><a href="#m7">testDevices</a></td></tr><tr class="failedodd"><td rowspan="7">com.perfectomobile.NativeExe</td><td><a href="#m8">testDevices</a></td><td rowspan="7">1451401720763</td><td rowspan="7">63072</td></tr><tr class="failedodd"><td><a href="#m9">testDevices</a></td></tr><tr class="failedodd"><td><a href="#m10">testDevices</a></td></tr><tr class="failedodd"><td><a href="#m11">testDevices</a></td></tr><tr class="failedodd"><td><a href="#m12">testDevices</a></td></tr><tr class="failedodd"><td><a href="#m13">testDevices</a></td></tr><tr class="failedodd"><td><a href="#m14">testDevices</a></td></tr><tr><th colspan="4">myTest &#8212; passed</th></tr><tr class="passedeven"><td rowspan="1">com.perfectomobile.BuildDevicesList</td><td><a href="#m15">deviceList</a></td><td rowspan="1">1451401718548</td><td rowspan="1">2193</td></tr><tr class="passedodd"><td rowspan="1">com.perfectomobile.NativeExe</td><td><a href="#m16">testDevices</a></td><td rowspan="1">1451401720763</td><td rowspan="1">62727</td></tr></tbody></table><h2>myTest</h2><h3 id="m0">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>ios</td><td>753CE046572094378A8CB5D91BC262613969596F</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m1">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>Android</td><td>9B99B8B1</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m2">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>Android</td><td>LGD850961FEC7B</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m3">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>ios</td><td>EA2D3BF43555096BEAAE3E9AA6DAA57CECB49485</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m4">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>Android</td><td>02157DF2CC01C136</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m5">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>ios</td><td>7BF8C558195939D244E20AF8E265DAF59B540E30</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m6">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>Android</td><td>012861923FDC3846</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m7">com.perfectomobile.DomExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th></tr><tr class="param stripe"><td>Android</td><td>D1EB6319</td><td>community.perfectomobile.com</td><td>null</td></tr><tr><th colspan="4">Exception</th></tr><tr><td colspan="4"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m8">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>Android</td><td>com.bloomfire.android.perfecto</td><td>D1EB6319</td><td>null</td><td>PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m9">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>Android</td><td>com.bloomfire.android.perfecto</td><td>9B99B8B1</td><td>null</td><td>PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m10">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>Android</td><td>com.bloomfire.android.perfecto</td><td>LGD850961FEC7B</td><td>null</td><td>PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m11">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>ios</td><td>com.bloomfire.enterprise.perfecto</td><td>7BF8C558195939D244E20AF8E265DAF59B540E30</td><td>null</td><td>PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m12">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>Android</td><td>com.bloomfire.android.perfecto</td><td>012861923FDC3846</td><td>null</td><td>PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m13">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>ios</td><td>com.bloomfire.enterprise.perfecto</td><td>EA2D3BF43555096BEAAE3E9AA6DAA57CECB49485</td><td>null</td><td>PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m14">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>ios</td><td>com.bloomfire.enterprise.perfecto</td><td>753CE046572094378A8CB5D91BC262613969596F</td><td>null</td><td>PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa</td></tr><tr><th colspan="5">Exception</th></tr><tr><td colspan="5"><div class="stacktrace">java.lang.AssertionError: Test Ended with error
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m15">com.perfectomobile.BuildDevicesList#deviceList</h3><table class="result"></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m16">com.perfectomobile.NativeExe#testDevices</h3><table class="result"><tr class="param"><th>Parameter #1</th><th>Parameter #2</th><th>Parameter #3</th><th>Parameter #4</th><th>Parameter #5</th></tr><tr class="param stripe"><td>Android</td><td>com.bloomfire.android.perfecto</td><td>02157DF2CC01C136</td><td>null</td><td>PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk</td></tr></table><p class="totop"><a href="#summary">back to summary</a></p></body></html>